# Generated by Django 3.1b1 on 2020-07-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ids',
            field=models.IntegerField(default=0),
        ),
    ]
