# Generated by Django 3.1b1 on 2020-07-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='contant',
            field=models.TextField(default='nothin'),
        ),
    ]
