# Generated by Django 3.1b1 on 2020-07-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_search_contant'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='contant2',
            field=models.TextField(default='nothin'),
        ),
        migrations.AddField(
            model_name='search',
            name='contant3',
            field=models.TextField(default='nothin'),
        ),
        migrations.AddField(
            model_name='search',
            name='ids2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='ids3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='name2',
            field=models.TextField(default='unNamed'),
        ),
        migrations.AddField(
            model_name='search',
            name='name3',
            field=models.TextField(default='unNamed'),
        ),
        migrations.AddField(
            model_name='search',
            name='search2',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='search',
            name='search3',
            field=models.TextField(default='none'),
        ),
    ]
