# Generated by Django 3.1b1 on 2020-07-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20200707_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='contant2',
        ),
        migrations.RemoveField(
            model_name='search',
            name='contant3',
        ),
        migrations.RemoveField(
            model_name='search',
            name='ids2',
        ),
        migrations.RemoveField(
            model_name='search',
            name='ids3',
        ),
        migrations.RemoveField(
            model_name='search',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='search',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='search',
            name='search2',
        ),
        migrations.RemoveField(
            model_name='search',
            name='search3',
        ),
    ]
